Repository CodeForAfrica/HURUmap-apps, pull requests merged in 2019-07, with the labels that each got.

#195 Upgrade HURUmap
  Dockerfile
Labels: bug

#196 [Bug] Fix exception catching
  hurumap_ke/profiles/census.py
  hurumap_tz/profiles/census.py
  hurumap_zm/profiles.py
  hurumap_zw/profiles/census.py
Labels: bug, data

#197 [Dominion] [ZA] Fix worker hostel tables' geo data
  dominion/profiles/land.py
  dominion/settings.py
  dominion/sql/workers_hostel_access_electricity.sql
  dominion/sql/workers_hostel_age_group.sql
  dominion/sql/workers_hostel_gender.sql
  dominion/sql/workers_hostel_geography.sql
  dominion/sql/workers_hostel_handwashing_facility.sql
  dominion/sql/workers_hostel_living_condition.sql
  dominion/sql/workers_hostel_ownership.sql
  dominion/sql/workers_hostel_population.sql
  dominion/sql/workers_hostel_population_group.sql
  dominion/sql/workers_hostel_rent.sql
  dominion/sql/workers_hostel_residential_ownership.sql
  dominion/sql/workers_hostel_ss_dwelling.sql
  dominion/sql/workers_hostel_subsidy.sql
  dominion/sql/workers_hostel_toilet_facility.sql
  dominion/sql/workers_hostel_water_source.sql
  hurumap_land/profiles/land.py
Labels: bug, data

#199 [Dominion] [ZA] Fix missing North West 2016 population data
  dominion/sql/population_group_2016.sql
Labels: bug, data

#201 [NG] Address Feedback 2
  hurumap_ng/settings.py
  hurumap_ng/static/img/logo-white.png
  hurumap_ng/templates/_base.html
  hurumap_ng/templates/_footer.html
  hurumap_ng/templates/about.html
  hurumap_ng/templates/blocks/partners.html
  hurumap_ng/templates/homepage.html
Labels: bug, enhancement

#202 Add Insights page
  hurumap_ng/settings.py
  hurumap_ng/static/css/ng.scss
  hurumap_ng/static/img/logo-white.png
  hurumap_ng/static/img/logo-white_insights.png
  hurumap_ng/static/img/logos/nbs.png
  hurumap_ng/static/img/nbs.png
  hurumap_ng/templates/_base.html
  hurumap_ng/templates/_footer.html
  hurumap_ng/templates/insights.html
  hurumap_ng/urls.py
  hurumap_ng/views.py
Labels: bug, enhancement

#204 [Hotfix] Update NBS logos
  hurumap_ng/settings.py
  hurumap_ng/static/img/logos/nbs.png
  hurumap_ng/static/img/nbs.png
  hurumap_ng/static/img/showcase/nbs.jpg
  hurumap_ng/static/img/showcase/nbs.png
Labels: bug, enhancement

#205 [Hotfix] [NG] Change insight
  hurumap_ng/templates/insights.html
Labels: bug, enhancement

#221 [NG] Adding more
  hurumap_ng/fixtures/hurumap_ng.json
  hurumap_ng/profiles.py
  hurumap_ng/settings.py
  hurumap_ng/sql/access_to_wash.sql
  hurumap_ng/sql/adolescent_fertility.sql
  hurumap_ng/sql/air_transportation_domestic.sql
  hurumap_ng/sql/air_transportation_international.sql
  hurumap_ng/sql/avg_number_bribes.sql
  hurumap_ng/sql/bank_credit.sql
  hurumap_ng/sql/bank_deposit.sql
  hurumap_ng/sql/birth_registration.sql
  hurumap_ng/sql/bribery_prevalence.sql
  hurumap_ng/sql/case_of_corruption.sql
  hurumap_ng/sql/compiled_hd_indeces.sql
  hurumap_ng/sql/consumer_price_index.sql
  hurumap_ng/sql/contraceptive_use.sql
  hurumap_ng/sql/crime_summary.sql
  hurumap_ng/sql/diseal_yearly.sql
  hurumap_ng/sql/domestic_flights.sql
  hurumap_ng/sql/driver_licences_processed.sql
  hurumap_ng/sql/drug_arrests.sql
  hurumap_ng/sql/drug_convictions.sql
  hurumap_ng/sql/drug_counselling.sql
  hurumap_ng/sql/drug_use.sql
  hurumap_ng/sql/employment_in_civil_services.sql
  hurumap_ng/sql/faac_yearly.sql
  hurumap_ng/sql/fertility_rate.sql
  hurumap_ng/sql/food_price.sql
  hurumap_ng/sql/governor_deputy_governor.sql
  hurumap_ng/sql/groundnut_production.sql
  hurumap_ng/sql/hdi_education.sql
  hurumap_ng/sql/hiv_arvs.sql
  hurumap_ng/sql/immunization_coverage.sql
  hurumap_ng/sql/international_flights.sql
  hurumap_ng/sql/junior_secondary_school_enrollment.sql
  hurumap_ng/sql/labour_force.sql
  hurumap_ng/sql/number_of_officials.sql
  hurumap_ng/sql/number_of_plates.sql
  hurumap_ng/sql/offences_against_authority.sql
  hurumap_ng/sql/offences_against_person.sql
  hurumap_ng/sql/offences_against_property.sql
  hurumap_ng/sql/officer_house_assembly.sql
  hurumap_ng/sql/passport_application.sql
  hurumap_ng/sql/passport_issued.sql
  hurumap_ng/sql/passport_re_issued.sql
  hurumap_ng/sql/population_projection.sql
  hurumap_ng/sql/postal_data.sql
  hurumap_ng/sql/primary_school_enrollment.sql
  hurumap_ng/sql/prison_population.sql
  hurumap_ng/sql/reported_bribery.sql
  hurumap_ng/sql/road_traffic_accidents.sql
  hurumap_ng/sql/senior_secondary_school_enrollment.sql
  hurumap_ng/sql/technical_school.sql
  hurumap_ng/sql/travel_certificates.sql
  hurumap_ng/sql/uder_employment_rate.sql
  hurumap_ng/sql/underweight_children.sql
  hurumap_ng/sql/unemployment_rate.sql
  hurumap_ng/sql/vaccine_coverage.sql
  hurumap_ng/templates/profile/profile_detail.html
Labels: data, enhancement

#225 [NG] Address round 3 of feedback
  hurumap_ng/profiles.py
  hurumap_ng/settings.py
  hurumap_ng/static/img/logo-white.png
  hurumap_ng/static/img/logos/brown.png
  hurumap_ng/static/img/logos/nbs-white.png
  hurumap_ng/static/img/logos/nbs.png
  hurumap_ng/static/img/showcase/gas.jpg
  hurumap_ng/static/img/showcase/nbs.png
  hurumap_ng/static/img/showcase/story-cooking-gas-2.jpg
  hurumap_ng/static/img/showcase/story-foodstuff-prices-2.jpg
  hurumap_ng/static/img/showcase/story-nigeria-gdp.jpg
  hurumap_ng/templates/_footer.html
  hurumap_ng/templates/blocks/partners.html
  hurumap_ng/templates/profile/profile_detail.html
Labels: bug

#226 [TZ][Bug] Fix Navigation (Profile) Tabs
  hurumap_tz/profiles/census.py
  hurumap_tz/templates/profile/profile_detail.html
Labels: bug

#229 [NG] Fix Charts & Data Issues from Feedback Docs
  hurumap_ng/fixtures/hurumap_ng.json
  hurumap_ng/profiles.py
  hurumap_ng/sql/external_domestic_debt.sql
  hurumap_ng/sql/literacy.sql
  hurumap_ng/sql/maternal_mortality.sql
  hurumap_ng/sql/mobile_subscription.sql
  hurumap_ng/sql/nominal_gdp.sql
  hurumap_ng/sql/number_of_dentists.sql
  hurumap_ng/sql/number_of_doctors.sql
  hurumap_ng/sql/population_sex.sql
  hurumap_ng/sql/telecom_subscription.sql
  hurumap_ng/templates/profile/profile_detail.html
Labels: bug
