Repository CodeForAfrica/HURUmap-apps, pull requests merged in 2019-03, with the labels that each got.

#145 [Dominion] Landing Page Review
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/assets/images/Showcase/background.png
  dominion/dominion_ui/src/assets/images/image.png
  dominion/dominion_ui/src/assets/images/image@2x.png
  dominion/dominion_ui/src/assets/images/image@3x.png
  dominion/dominion_ui/src/assets/images/image_2.png
  dominion/dominion_ui/src/assets/images/image_2@2x.png
  dominion/dominion_ui/src/assets/images/image_2@3x.png
  dominion/dominion_ui/src/assets/images/image_3.png
  dominion/dominion_ui/src/assets/images/image_3@2x.png
  dominion/dominion_ui/src/assets/images/image_3@3x.png
  dominion/dominion_ui/src/assets/images/image_4.png
  dominion/dominion_ui/src/assets/images/image_4@2x.png
  dominion/dominion_ui/src/assets/images/image_4@3x.png
  dominion/dominion_ui/src/assets/images/kaitlyn-baker-422999-unsplash.png
  dominion/dominion_ui/src/assets/images/kaitlyn-baker-422999-unsplash@2x.png
  dominion/dominion_ui/src/assets/images/kaitlyn-baker-422999-unsplash@3x.png
  dominion/dominion_ui/src/components/About/Header.js
  dominion/dominion_ui/src/components/About/Info.js
  dominion/dominion_ui/src/components/About/Land.js
  dominion/dominion_ui/src/components/About/index.js
  dominion/dominion_ui/src/components/Data/Content.js
  dominion/dominion_ui/src/components/Data/Documents.js
  dominion/dominion_ui/src/components/Data/index.js
  dominion/dominion_ui/src/components/Footer/About.js
  dominion/dominion_ui/src/components/Footer/Community.js
  dominion/dominion_ui/src/components/Footer/Partners.js
  dominion/dominion_ui/src/components/Footer/Project.js
  dominion/dominion_ui/src/components/Footer/index.js
  dominion/dominion_ui/src/components/Partners.js
  dominion/dominion_ui/src/components/Showcase/Stories.js
  dominion/dominion_ui/src/components/Showcase/StoryCard.js
  dominion/dominion_ui/src/components/Showcase/StoryList.js
  dominion/dominion_ui/src/components/Showcase/index.js
  dominion/dominion_ui/src/components/Video/Player.js
  dominion/dominion_ui/src/components/Video/Thumbnail.js
  dominion/dominion_ui/src/components/Video/index.js
  dominion/dominion_ui/src/index.js
  dominion/static/css/dominion.scss
  dominion/templates/blocks/partners.html
  dominion/templates/homepage.html
Labels: bug, enhancement

#151 [Dominion] Country page
  dominion/settings.py
  dominion/templates/blocks/country_header.html
  dominion/templates/blocks/country_partners.html
  dominion/templates/country_page.html
  dominion/urls.py
  dominion/views.py
Labels: enhancement

#148 [Dominion] Country Page Hero
  .gitignore
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/public/static/img/background.png
  dominion/dominion_ui/src/assets/images/logos/dominion-logo-country.png
  dominion/dominion_ui/src/components/Header/Dropdown.js
  dominion/dominion_ui/src/components/Header/Header.js
  dominion/dominion_ui/src/components/Header/PortalDropdown.js
  dominion/dominion_ui/src/components/Header/Search.js
  dominion/dominion_ui/src/components/Header/index.js
  dominion/dominion_ui/src/components/Hero/CountryHero.js
  dominion/dominion_ui/src/components/Hero/Hero.js
  dominion/dominion_ui/src/components/Hero/HomeHero.js
  dominion/dominion_ui/src/components/Hero/HomeHeroMap.js
  dominion/dominion_ui/src/components/HomeHero/HeroDetail.js
  dominion/dominion_ui/src/components/HomeHero/index.js
  dominion/dominion_ui/src/components/Modal.js
  dominion/dominion_ui/src/components/Modal/GetLocation.js
  dominion/dominion_ui/src/components/Modal/PortalChooser.js
  dominion/dominion_ui/src/components/Modal/index.js
  dominion/dominion_ui/src/components/Search/SearchBar.js
  dominion/dominion_ui/src/components/Search/SearchResults.js
  dominion/dominion_ui/src/components/Search/index.js
  dominion/dominion_ui/src/index.js
  dominion/dominion_ui/src/slugify.js
  dominion/settings.py
  dominion/static/css/dominion.scss
  dominion/static/js/profile_map_mapit.js
  dominion/templates/blocks/country_header.html
  dominion/templates/blocks/countrypage_header.html
  dominion/templates/blocks/header.html
  dominion/templates/blocks/homepage_header.html
  dominion/templates/country_page.html
  dominion/templates/homepage.html
  dominion/templates/settings_js.html
  dominion/views.py
Labels: enhancement

#154 [Dominion] Profile Page Tabs
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/components/Partners.js
  dominion/dominion_ui/src/components/ProfileTabs.js
  dominion/dominion_ui/src/index.js
  dominion/static/css/dominion.scss
  dominion/templates/blocks/profilepage_header.html
  dominion/templates/profile/profile_detail.html
Labels: enhancement

#156 [Dominion] Modal to contain navigation component
  dominion/dominion_ui/src/components/Header/Header.js
  dominion/dominion_ui/src/components/Header/Navigation.js
  dominion/dominion_ui/src/components/Header/PortalDropdown.js
  dominion/dominion_ui/src/components/Modal/PortalChooser.js
  dominion/dominion_ui/src/components/Modal/index.js
  dominion/dominion_ui/src/components/Search/index.js
Labels: bug, enhancement

#153 [Dominion] Sub geo-level search for country page
  dominion/dominion_ui/package.json
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/api.js
  dominion/dominion_ui/src/components/Modal/GetLocation.js
  dominion/dominion_ui/src/components/Search/SearchResults.js
  dominion/dominion_ui/src/components/Search/index.js
  dominion/dominion_ui/src/slugify.js
Labels: enhancement

#160 [Dominion] Add country partner logo component
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/components/CountryPartners/PartnerContent.js
  dominion/dominion_ui/src/components/CountryPartners/index.js
  dominion/dominion_ui/src/index.js
Labels: enhancement

#155 [Dominion] Add How it Works Component
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/assets/images/icons/black-combined-shape.svg
  dominion/dominion_ui/src/components/HowItWorks/Content.js
  dominion/dominion_ui/src/components/HowItWorks/Description.js
  dominion/dominion_ui/src/components/HowItWorks/FindFactsContent.js
  dominion/dominion_ui/src/components/HowItWorks/GetContext.js
  dominion/dominion_ui/src/components/HowItWorks/Map.js
  dominion/dominion_ui/src/components/HowItWorks/Steps.js
  dominion/dominion_ui/src/components/HowItWorks/ViewVideos.js
  dominion/dominion_ui/src/components/HowItWorks/VisualizeContent.js
  dominion/dominion_ui/src/components/HowItWorks/index.js
  dominion/dominion_ui/src/components/OurPartners.js
  dominion/dominion_ui/src/index.js
Labels: enhancement

#157 [Dominion][Bug] Fix map tiles and draw children level
  dominion/static/js/profile_map_mapit.js
  dominion/templates/country_page.html
Labels: bug

#159 [Dominion] Video Modal
  dominion/dominion_ui/src/components/Header/Header.js
  dominion/dominion_ui/src/components/Header/Navigation.js
  dominion/dominion_ui/src/components/IFrame.js
  dominion/dominion_ui/src/components/Modal/index.js
  dominion/dominion_ui/src/components/Video/Player.js
  dominion/dominion_ui/src/components/Video/Thumbnail.js
  dominion/dominion_ui/src/components/Video/index.js
Labels: enhancement

#161 [Dominion] Profile Releases Section
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/assets/images/group-3-up.png
  dominion/dominion_ui/src/assets/images/group-3.png
  dominion/dominion_ui/src/components/ProfileReleases/index.js
  dominion/dominion_ui/src/index.js
  dominion/templates/profile/profile_detail.html
Labels: enhancement

#158 [Dominion] Profile Page Hero
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/api.js
  dominion/dominion_ui/src/components/Header/index.js
  dominion/dominion_ui/src/components/Hero/Hero.js
  dominion/dominion_ui/src/components/Hero/ProfileHero.js
  dominion/dominion_ui/src/components/ProfileReleases/index.js
  dominion/dominion_ui/src/components/ReleaseDropdown.js
  dominion/dominion_ui/src/components/Search/SearchBar.js
  dominion/dominion_ui/src/components/Search/SearchResults.js
  dominion/dominion_ui/src/components/Search/index.js
  dominion/dominion_ui/src/index.js
  dominion/fixtures/dominion.json
  dominion/settings.py
  dominion/static/css/dominion.scss
  dominion/static/js/map_mapit.js
  dominion/static/js/profile_map_mapit.js
  dominion/templates/_base.html
  dominion/templates/blocks/profilepage_header.html
  dominion/templates/country_page.html
  dominion/templates/profile/head2head.html
  dominion/templates/profile/profile_detail.html
  dominion/templates/settings_js.html
Labels: enhancement

#166 [Dominion]Fix country partner logos
  dominion/dominion_ui/src/components/CountryPartners/index.js
Labels: bug, enhancement

#164 [Dominion] Fixes - logo, map, footer on profile
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/components/Header/Navigation.js
  dominion/dominion_ui/src/components/Modal/index.js
  dominion/dominion_ui/src/components/Search/SearchResults.js
  dominion/dominion_ui/src/components/Video/index.js
  dominion/static/css/dominion.scss
  dominion/static/js/map_mapit.js
  dominion/static/js/profile_map_mapit.js
  dominion/templates/about.html
  dominion/templates/profile/profile_detail.html
  dominion/templates/settings_js.html
Labels: bug, enhancement

#163 [Dominion] Population Data
  dominion/data/__init__.py
  dominion/data/utils.py
  dominion/dominion_ui/src/components/Hero/ProfileHero.js
  dominion/fixtures/dominion.json
  dominion/profiles/land.py
  dominion/settings.py
  dominion/sql/population_group_2016.sql
  dominion/sql/population_residence_2009.sql
  dominion/sql/populationgroup_2016.sql
  dominion/templates/settings_js.html
Labels: enhancement

#167 [Dominion] Fix how it works video modal
  dominion/dominion_ui/src/components/HowItWorks/Description.js
  dominion/dominion_ui/src/components/Video/index.js
Labels: bug

#170 Video Modal Missing Navigation Bar
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/components/HowItWorks/Description.js
  dominion/dominion_ui/src/components/Video/Player.js
  dominion/dominion_ui/src/components/Video/PlayerModal.js
  dominion/dominion_ui/src/components/Video/index.js
Labels: bug

#165 [Dominion] Add comparison profile page
  dominion/dominion_ui/src/components/Header/index.js
  dominion/dominion_ui/src/components/Hero/Hero.js
  dominion/dominion_ui/src/components/Hero/ProfileHero.js
  dominion/dominion_ui/src/index.js
  dominion/static/css/dominion.scss
  dominion/static/img/background.png
  dominion/templates/profile/head2head.html
  dominion/templates/profile/profile_detail.html
  dominion/templates/settings_js.html
  dominion/urls.py
  dominion/views.py
Labels: enhancement

#171 [Dominion] Releases per country
  dominion/dominion_ui/src/components/Hero/ProfileHero.js
  dominion/urls.py
  dominion/views.py
Labels: bug

#162 [Dominion] Externalize component content
  dominion/dominion_ui/package.json
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/api.js
  dominion/dominion_ui/src/components/About/AboutCountry.js
  dominion/dominion_ui/src/components/About/Data.js
  dominion/dominion_ui/src/components/About/Header.js
  dominion/dominion_ui/src/components/About/Info.js
  dominion/dominion_ui/src/components/About/Land.js
  dominion/dominion_ui/src/components/Data/Content.js
  dominion/dominion_ui/src/components/Data/DatasetsContent.js
  dominion/dominion_ui/src/components/Data/DocumentsContents.js
  dominion/dominion_ui/src/components/Header/Header.js
  dominion/dominion_ui/src/components/Header/Navigation.js
  dominion/dominion_ui/src/components/Header/PortalDropdown.js
  dominion/dominion_ui/src/components/Header/index.js
  dominion/dominion_ui/src/components/Hero/CountryHero.js
  dominion/dominion_ui/src/components/Hero/Hero.js
  dominion/dominion_ui/src/components/Hero/HomeHero.js
  dominion/dominion_ui/src/components/Hero/HomeHeroMap.js
  dominion/dominion_ui/src/components/Hero/ProfileHero.js
  dominion/dominion_ui/src/components/HowItWorks/Description.js
  dominion/dominion_ui/src/components/HowItWorks/index.js
  dominion/dominion_ui/src/components/Modal/GetLocation.js
  dominion/dominion_ui/src/components/Modal/PortalChooser.js
  dominion/dominion_ui/src/components/Modal/index.js
  dominion/dominion_ui/src/components/ProfileReleases/index.js
  dominion/dominion_ui/src/components/ProfileTabs.js
  dominion/dominion_ui/src/components/ReleaseDropdown.js
  dominion/dominion_ui/src/components/Search/SearchBar.js
  dominion/dominion_ui/src/components/Search/SearchResults.js
  dominion/dominion_ui/src/components/Search/index.js
  dominion/dominion_ui/src/components/Video/PlayerModal.js
  dominion/dominion_ui/src/components/Video/index.js
  dominion/dominion_ui/src/index.js
  dominion/dominion_ui/yarn.lock
  dominion/sql/population_group_2016.sql
  dominion/static/css/dominion.scss
  dominion/static/js/map_mapit.js
  dominion/templates/profile/head2head.html
  dominion/templates/settings_js.html
  dominion/urls.py
  dominion/views.py
Labels: bug, enhancement

#168 [Dominion] South african land data
  dominion/dominion_ui/src/components/ProfileTabs.js
  dominion/fixtures/dominion.json
  dominion/profiles/land.py
  dominion/settings.py
  dominion/sql/access_to_information.sql
  dominion/sql/allow_farmers_retain_land_ownership.sql
  dominion/sql/erven_land_ownership_in_hectares_by_gender.sql
  dominion/sql/erven_land_ownership_in_hectares_by_nationality.sql
  dominion/sql/erven_land_ownership_in_hectares_by_race.sql
  dominion/sql/hectares_transferred_per_province_by_year.sql
  dominion/sql/land_acquisation_challenges.sql
  dominion/sql/land_to_prioritise_for_redistribution.sql
  dominion/sql/land_traded_all_vs_colour_2018.sql
  dominion/sql/land_traded_colour_cost_breakdown_2018.sql
  dominion/sql/land_traded_colour_hectares_breakdown_2018.sql
  dominion/sql/land_traded_colour_priceperhectare_breakdown_2018.sql
  dominion/sql/land_traded_colour_transactions_2018.sql
  dominion/sql/land_traded_per_class_statistic_2018.sql
  dominion/sql/landownership.sql
  dominion/sql/landownershipinhectaresbygender.sql
  dominion/sql/landownershipinhectaresbynationality.sql
  dominion/sql/landownershipinhectaresbyrace.sql
  dominion/sql/landuse.sql
  dominion/sql/landuser.sql
  dominion/sql/maintain_willing_buyer_willing_seller_policy.sql
  dominion/sql/number_of_erven_land_owners_per_gender.sql
  dominion/sql/number_of_erven_land_owners_per_nationality.sql
  dominion/sql/number_of_erven_land_owners_per_race.sql
  dominion/sql/numberoflandownerspergender.sql
  dominion/sql/numberoflandownerspernationality.sql
  dominion/sql/numberoflandownersperrace.sql
  dominion/sql/numberofprivatelandownersbycategory.sql
  dominion/sql/numberofsectionaltitleownersbycategory.sql
  dominion/sql/numberofsectionaltitleownersbygender.sql
  dominion/sql/numberofsectionaltitleownersbynationality.sql
  dominion/sql/numberofsectionaltitleownersbyrace.sql
  dominion/sql/party_benefited.sql
  dominion/sql/population.sql
  dominion/sql/population_group_2016.sql
  dominion/sql/privatelanddistributionbygender.sql
  dominion/sql/privatelandownershipinhectares.sql
  dominion/sql/privatelandownershipinhectarespercategory.sql
  dominion/sql/redistributedlandcostinrands.sql
  dominion/sql/redistributedlandinhectares.sql
  dominion/sql/redistributedlandusebreakdown.sql
  dominion/sql/redistributionprogrammeoutcomebyear.sql
  dominion/sql/restitutionoutcomestatic.sql
  dominion/sql/sectionaltitleownershipinhectarespercategory.sql
  dominion/sql/sectionaltitleownershipinhectarespergender.sql
  dominion/sql/sectionaltitleownershipinhectarespernationality.sql
  dominion/sql/sectionaltitleownershipinhectaresperrace.sql
  dominion/static/css/dominion.scss
  dominion/templates/profile/profile_detail.html
Labels: enhancement
