Repository CodeForAfrica/HURUmap-apps, pull requests merged in 2019-06, with the labels that each got.

#184 Ensure each app has unique Google Analytics id
  dominion/settings.py
  hurumap_land/settings.py
Labels: bug, enhancement

#186 [Hotfix] Share GA ID between Dominion & Land
  dominion/settings.py
Labels: enhancement

#182 HURUmap Nigeria Instance
  dominion/dominion_ui/build/precache-manifest.9c825716a7cd582bb916da34a797ed54.js
  dominion/dominion_ui/build/static/js/1.14872407.chunk.js
  dominion/dominion_ui/build/static/js/1.14872407.chunk.js.map
  dominion/dominion_ui/build/static/js/main.6fe04a97.chunk.js
  dominion/dominion_ui/build/static/js/main.6fe04a97.chunk.js.map
  dominion/dominion_ui/build/static/media/image.0c3cbd5b.png
  dominion/dominion_ui/build/static/media/image_2.17242cbd.png
  dominion/dominion_ui/build/static/media/image_3.91f51595.png
  dominion/dominion_ui/build/static/media/image_4.330cc9dd.png
  hurumap_ng/__init__.py
  hurumap_ng/fixtures/hurumap_ng.json
  hurumap_ng/profiles.py
  hurumap_ng/settings.py
  hurumap_ng/sql/external_domestic_debt.sql
  hurumap_ng/sql/wazimap_geography.sql
  hurumap_ng/static/img/examples/hover_over_graph.png
  hurumap_ng/static/img/examples/map_search.png
  hurumap_ng/static/img/examples/section_overview.png
  hurumap_ng/static/img/examples/text_search.png
  hurumap_ng/static/img/logo-white.png
  hurumap_ng/static/img/logo.png
  hurumap_ng/static/img/logos/nan.png
  hurumap_ng/static/img/logos/nbs.png
  hurumap_ng/static/img/showcase/gas.jpg
  hurumap_ng/static/img/showcase/nbs.jpg
  hurumap_ng/tables.py
  hurumap_ng/templates/_base.html
  hurumap_ng/templates/_footer.html
  hurumap_ng/templates/about.html
  hurumap_ng/templates/blocks/partners.html
  hurumap_ng/templates/homepage.html
  hurumap_ng/templates/profile/profile_detail.html
  hurumap_ng/urls.py
Labels: enhancement

#185 [LAND] Adding Drone Hostels Data
  hurumap_land/fixtures/hurumap_land.json
  hurumap_land/profiles/land.py
  hurumap_land/settings.py
  hurumap_land/sql/workers_hostel_access_electricity.sql
  hurumap_land/sql/workers_hostel_age_group.sql
  hurumap_land/sql/workers_hostel_gender.sql
  hurumap_land/sql/workers_hostel_geography.sql
  hurumap_land/sql/workers_hostel_handwashing_facility.sql
  hurumap_land/sql/workers_hostel_living_condition.sql
  hurumap_land/sql/workers_hostel_ownership.sql
  hurumap_land/sql/workers_hostel_population.sql
  hurumap_land/sql/workers_hostel_population_group.sql
  hurumap_land/sql/workers_hostel_rent.sql
  hurumap_land/sql/workers_hostel_residential_ownership.sql
  hurumap_land/sql/workers_hostel_ss_dwelling.sql
  hurumap_land/sql/workers_hostel_subsidy.sql
  hurumap_land/sql/workers_hostel_toilet_facility.sql
  hurumap_land/sql/workers_hostel_water_source.sql
  hurumap_land/tables.py
  hurumap_land/templates/profile/profile_detail.html
Labels: data, enhancement

#187 [NG] Add NBS data
  hurumap_ng/fixtures/hurumap_ng.json
  hurumap_ng/profiles.py
  hurumap_ng/settings.py
  hurumap_ng/sql/arrested_suspects.sql
  hurumap_ng/sql/conviction_secured.sql
  hurumap_ng/sql/counselling_concluded.sql
  hurumap_ng/sql/diesel_price.sql
  hurumap_ng/sql/drugs_seized.sql
  hurumap_ng/sql/faac.sql
  hurumap_ng/sql/food_price.sql
  hurumap_ng/sql/hiv_patient.sql
  hurumap_ng/sql/jamb.sql
  hurumap_ng/sql/mineral_production.sql
  hurumap_ng/sql/mobile_subscription.sql
  hurumap_ng/sql/petrol_price.sql
  hurumap_ng/sql/suspects_prosecuted.sql
  hurumap_ng/sql/telecom_subscription.sql
  hurumap_ng/sql/wazimap_geography.sql
  hurumap_ng/tables.py
  hurumap_ng/templates/profile/profile_detail.html
Labels: data, enhancement

#189 [Dominion] Add Drone Workers Hostel Data
  dominion/dominion_ui/build/asset-manifest.json
  dominion/dominion_ui/build/favicons/darkgrey/android-chrome-192x192.png
  dominion/dominion_ui/build/favicons/darkgrey/android-chrome-512x512.png
  dominion/dominion_ui/build/favicons/darkgrey/apple-touch-icon.png
  dominion/dominion_ui/build/favicons/darkgrey/browserconfig.xml
  dominion/dominion_ui/build/favicons/darkgrey/favicon-16x16.png
  dominion/dominion_ui/build/favicons/darkgrey/favicon-32x32.png
  dominion/dominion_ui/build/favicons/darkgrey/favicon.ico
  dominion/dominion_ui/build/favicons/darkgrey/manifest.json
  dominion/dominion_ui/build/favicons/darkgrey/mstile-150x150.png
  dominion/dominion_ui/build/favicons/darkgrey/safari-pinned-tab.svg
  dominion/dominion_ui/build/index.html
  dominion/dominion_ui/build/manifest.json
  dominion/dominion_ui/build/service-worker.js
  dominion/dominion_ui/build/static/img/background.png
  dominion/dominion_ui/build/static/js/runtime~main.229c360f.js
  dominion/dominion_ui/build/static/js/runtime~main.229c360f.js.map
  dominion/dominion_ui/build/static/media/back.a0fb01e1.svg
  dominion/dominion_ui/build/static/media/background.9283b78c.png
  dominion/dominion_ui/build/static/media/black-combined-shape.d78e63d8.svg
  dominion/dominion_ui/build/static/media/bmgf.c68bf410.png
  dominion/dominion_ui/build/static/media/close.ad780f28.svg
  dominion/dominion_ui/build/static/media/codeforafrica.bda4db84.png
  dominion/dominion_ui/build/static/media/combined-shape.a2c0a988.svg
  dominion/dominion_ui/build/static/media/databg.345f88e8.png
  dominion/dominion_ui/build/static/media/dominion-logo-country.335659fb.png
  dominion/dominion_ui/build/static/media/dominion-logo.f1b8c0d0.png
  dominion/dominion_ui/build/static/media/hero-image-1.6696e147.png
  dominion/dominion_ui/build/static/media/hero-image-3.fb06e88b.png
  dominion/dominion_ui/build/static/media/hero-image-3_2.38a29f89.png
  dominion/dominion_ui/build/static/media/hero_bg.61556081.png
  dominion/dominion_ui/build/static/media/hero_map.3dc6948e.png
  dominion/dominion_ui/build/static/media/icfj.37dfe5cb.png
  dominion/dominion_ui/build/static/media/kaitlyn-baker-422999-unsplash.3b2e31dd.png
  dominion/dominion_ui/build/static/media/location.d4ddacef.svg
  dominion/dominion_ui/build/static/media/menu.32556f49.svg
  dominion/dominion_ui/build/static/media/shape.ca30e81a.svg
  dominion/dominion_ui/build/static/media/smallscreen_background.fe708168.png
  dominion/dominion_ui/build/static/media/twaweza.bb78f01e.png
  dominion/fixtures/dominion.json
  dominion/profiles/land.py
  dominion/settings.py
  dominion/sql/workers_hostel_access_electricity.sql
  dominion/sql/workers_hostel_age_group.sql
  dominion/sql/workers_hostel_gender.sql
  dominion/sql/workers_hostel_geography.sql
  dominion/sql/workers_hostel_handwashing_facility.sql
  dominion/sql/workers_hostel_living_condition.sql
  dominion/sql/workers_hostel_ownership.sql
  dominion/sql/workers_hostel_population.sql
  dominion/sql/workers_hostel_population_group.sql
  dominion/sql/workers_hostel_rent.sql
  dominion/sql/workers_hostel_residential_ownership.sql
  dominion/sql/workers_hostel_ss_dwelling.sql
  dominion/sql/workers_hostel_subsidy.sql
  dominion/sql/workers_hostel_toilet_facility.sql
  dominion/sql/workers_hostel_water_source.sql
  dominion/templates/profile/profile_detail.html
  dominion/templates/settings_js.html
Labels: data, enhancement
