Repository CodeForAfrica/HURUmap-apps, pull requests merged in 2019-02, with the labels that each got.

#117 [Dominion] [Site] Footer
  dominion/frontend/.eslintrc.json
  dominion/frontend/src/assets/images/bg/background.png
  dominion/frontend/src/assets/images/logos/bmgf.png
  dominion/frontend/src/assets/images/logos/codeforafrica.png
  dominion/frontend/src/assets/images/logos/datazetu.png
  dominion/frontend/src/assets/images/logos/icfj.png
  dominion/frontend/src/assets/images/logos/twaweza.png
  dominion/frontend/src/component/Footer/Partners.js
  dominion/frontend/src/component/Footer/index.js
  dominion/frontend/src/component/SocialMedia.js
  dominion/frontend/src/index.js
  dominion/frontend/src/pages/Home.js
Labels: enhancement

#121 [Dominion] [Site] Landing Page Showcase Component
  dominion/frontend/.eslintrc.json
  dominion/frontend/public/404.html
  dominion/frontend/public/index.html
  dominion/frontend/src/App.js
  dominion/frontend/src/assets/images/Showcase/background.png
  dominion/frontend/src/component/Footer/About.js
  dominion/frontend/src/component/Footer/Partners.js
  dominion/frontend/src/component/Footer/index.js
  dominion/frontend/src/component/Showcase/Stories.js
  dominion/frontend/src/component/Showcase/StoryCard.js
  dominion/frontend/src/component/Showcase/StoryList.js
  dominion/frontend/src/component/Showcase/index.js
  dominion/frontend/src/pages/Home.js
Labels: enhancement

#124 [Dominion] [Site] Fix styling Update [163284275]
  dominion/frontend/src/App.js
  dominion/frontend/src/component/Showcase/StoryCard.js
Labels: bug, enhancement

#122 Implementing Mapit
  Dockerfile
  docker-compose.yml
  elimu_yangu/settings.py
  elimu_yangu/static/js/profile_map.js
  elimu_yangu/templates/homepage_country.html
  hurumap_ke/settings.py
  hurumap_tz/settings.py
  hurumap_ug/settings.py
  hurumap_zm/settings.py
  hurumap_zw/settings.py
  pesayetu/settings.py
Labels: enhancement

#132 Fix "Use Your Current Location"
  Dockerfile
  hurumap_global/settings.py
  hurumap_global/templates/homepage.html
Labels: bug, enhancement

#136 [ElimuYangu] Bug Fixes
  docker-compose.yml
  elimu_yangu/careerguide/templates/careerguide/homepage.html
  elimu_yangu/careerguide/views.py
  elimu_yangu/leaguetable/templates/leaguetable/profile/head2head.html
  elimu_yangu/leaguetable/urls.py
  elimu_yangu/leaguetable/views.py
  elimu_yangu/settings.py
  elimu_yangu/static/css/site.css
  elimu_yangu/static/js/site.js
  elimu_yangu/static/js/widget.geo.select.js
  elimu_yangu/static/lib/owlcarousel/css/owl.carousel.css
  elimu_yangu/static/lib/owlcarousel/css/owl.theme.css
  elimu_yangu/templates/footer.html
  elimu_yangu/templates/homepage.html
  elimu_yangu/templates/homepage_country.html
  elimu_yangu/urls.py
Labels: bug

#133 Agrids land sales update
  docker-compose.yml
  hurumap_land/fixtures/hurumap_land.json
  hurumap_land/profiles/land.py
  hurumap_land/script/agrids_distribution.py
  hurumap_land/script/agrids_district_Statistic.py
  hurumap_land/script/agrids_summary.py
  hurumap_land/script/towndistrictcodemapping.json
  hurumap_land/script/towndistrictlevelmapping.json
  hurumap_land/settings.py
  hurumap_land/sql/land_traded_all_vs_colour_2018.sql
  hurumap_land/sql/land_traded_colour_cost_breakdown_2018.sql
  hurumap_land/sql/land_traded_colour_hectares_breakdown_2018.sql
  hurumap_land/sql/land_traded_colour_priceperhectare_breakdown_2018.sql
  hurumap_land/sql/land_traded_colour_transactions_2018.sql
  hurumap_land/sql/land_traded_per_class_statistic_2018.sql
  hurumap_land/sql/landsalesdistribution.sql
  hurumap_land/sql/town_district_land_traded_statistic_2018.sql
  hurumap_land/templates/profile/profile_detail.html
Labels: enhancement

#139 [Dominion] Homepage Data Component
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/components/Data/index.js
  dominion/dominion_ui/src/index.js
  dominion/templates/homepage.html
Labels: enhancement

#140 Add and fix about dominion component
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/Theme.js
  dominion/dominion_ui/src/components/About/Header.js
  dominion/dominion_ui/src/components/About/Info.js
  dominion/dominion_ui/src/components/About/Land.js
  dominion/dominion_ui/src/components/About/index.js
  dominion/dominion_ui/src/index.js
  dominion/templates/homepage.html
Labels: enhancement

#128 [Dominion] Video Component
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/assets/images/hero-image-1.png
  dominion/dominion_ui/src/assets/images/hero-image-1@2x.png
  dominion/dominion_ui/src/assets/images/hero-image-1@3x.png
  dominion/dominion_ui/src/components/IFrame.js
  dominion/dominion_ui/src/components/Video/Sources.js
  dominion/dominion_ui/src/components/Video/Thumbnail.js
  dominion/dominion_ui/src/components/Video/index.js
  dominion/dominion_ui/src/index.js
Labels: enhancement

#142 Add updated assets to datasets component
  dominion/dominion_ui/src/assets/images/bg/databg.png
  dominion/dominion_ui/src/assets/images/bg/databg@2x.png
  dominion/dominion_ui/src/assets/images/bg/databg@3x.png
  dominion/dominion_ui/src/assets/images/icons/group-6.png
  dominion/dominion_ui/src/assets/images/icons/group-6@2x.png
  dominion/dominion_ui/src/assets/images/icons/group-6@3x 2.png
  dominion/dominion_ui/src/assets/images/icons/group-6@3x.png
  dominion/dominion_ui/src/assets/images/icons/group-7.png
  dominion/dominion_ui/src/assets/images/icons/group-7@2x.png
  dominion/dominion_ui/src/assets/images/icons/group-7@3x.png
  dominion/dominion_ui/src/components/Data/Content.js
  dominion/dominion_ui/src/components/Data/DatasetsContent.js
  dominion/dominion_ui/src/components/Data/Documents.js
  dominion/dominion_ui/src/components/Data/DocumentsContents.js
  dominion/dominion_ui/src/components/Data/index.js
Labels: bug, enhancement
