Repository CodeForAfrica/HURUmap-apps, pull requests merged in 2019-04, with the labels that each got.

#169 Python 3 Upgrade
  Dockerfile
  docker-compose.yml
  dominion/context_processors.py
  dominion/profiles/land.py
  elimu_yangu/careerguide/forms.py
  elimu_yangu/careerguide/models.py
  elimu_yangu/careerguide/views.py
  elimu_yangu/profiles/census.py
  elimu_yangu/universityfinder/admin.py
  elimu_yangu/universityfinder/apps.py
  elimu_yangu/universityfinder/migrations/0001_initial.py
  elimu_yangu/universityfinder/models.py
  elimu_yangu/universityfinder/tests.py
  elimu_yangu/universityfinder/views.py
  hurumap_ke/profiles/census.py
  hurumap_land/geo.py
  hurumap_land/profiles/land.py
  hurumap_land/script/agrids_distribution.py
  hurumap_land/script/agrids_district_Statistic.py
  hurumap_land/script/agrids_summary.py
  hurumap_tz/profiles/census.py
  hurumap_ug/profiles/census.py
  pesayetu/profiles/pesayetu.py
Labels: enhancement

#175 [Dominion] Fix profile tabs hrefs + map zoom
  dominion/dominion_ui/src/components/ProfileTabs.js
  dominion/dominion_ui/src/index.js
  dominion/static/js/profile_map_mapit.js
  dominion/templates/profile/profile_detail.html
  dominion/templates/settings_js.html
Labels: bug, enhancement

#176 [Dominion] Update charts theme
  dominion/profiles/land.py
  dominion/settings.py
  dominion/static/css/dominion.scss
  dominion/templates/profile/profile_detail.html
Labels: enhancement

#178 [Dominion] Add missing test tabs data
  dominion/dominion_ui/public/index.html
Labels: bug

#179 [Dominion] Fix mobile navigation
  dominion/dominion_ui/src/components/Header/Navigation.js
Labels: bug

#177 [Dominion] Fix Homepage UI Bugs
  dominion/context_processors.py
  dominion/dominion_ui/public/index.html
  dominion/dominion_ui/src/Theme.js
  dominion/dominion_ui/src/components/Data/Content.js
  dominion/dominion_ui/src/components/Data/DatasetsContent.js
  dominion/dominion_ui/src/components/Data/Documents.js
  dominion/dominion_ui/src/components/Data/DocumentsContents.js
  dominion/dominion_ui/src/components/Data/index.js
  dominion/dominion_ui/src/components/Header/PortalDropdown.js
  dominion/dominion_ui/src/components/Hero/HomeHeroMap.js
  dominion/dominion_ui/src/components/OurPartners.js
  dominion/dominion_ui/src/components/Partners.js
  dominion/dominion_ui/src/components/Showcase/Stories.js
  dominion/dominion_ui/src/components/Showcase/StoryCard.js
  dominion/dominion_ui/src/components/Showcase/StoryList.js
  dominion/dominion_ui/src/components/Showcase/index.js
  dominion/dominion_ui/src/components/SocialMedia.js
  dominion/dominion_ui/src/components/SocialMedia.test.js
  dominion/dominion_ui/src/components/Video/index.js
  dominion/dominion_ui/src/index.js
  dominion/settings.py
  dominion/static/css/dominion.scss
  dominion/static/img/showcase/showcase1.jpg
  dominion/static/img/showcase/showcase2.jpg
  dominion/static/img/showcase/showcase3.jpg
  dominion/static/img/showcase/showcase4.jpg
  dominion/static/img/showcase/showcase5.jpg
  dominion/static/img/showcase/showcase6.jpg
  dominion/static/img/showcase/showcase7.jpg
  dominion/static/img/showcase/showcase8.jpg
  dominion/static/img/showcase/showcase9.jpg
  dominion/static/img/showcase/showcase_1.jpg
  dominion/static/img/showcase/showcase_2.jpg
  dominion/static/img/showcase/showcase_3.jpg
  dominion/templates/blocks/country_partners.html
  dominion/templates/blocks/countrypage_header.html
  dominion/templates/blocks/homepage_header.html
  dominion/templates/blocks/partners.html
  dominion/templates/blocks/profilepage_header.html
  dominion/templates/blocks/showcase.html
  dominion/templates/country_page.html
  dominion/templates/homepage.html
  dominion/templates/profile/profile_detail.html
  dominion/templates/settings_js.html
Labels: bug
